### ISSUE TITLE
Not working with npm@3

### ISSUE THREAD

**Issue by SamyPesse** [todvora/gitbook-tester#1]
NPM 3 is flattening dependencies, and so `node_modules/gitbook-tester/node_modules/.bin/gitbook` doesn't exists, instead it's `node_modules/.bin/gitbook`.

It'd be better to use `require.resolve` to determine the path.

**Comment by todvora** [comment]
Fixed in release 1.0.2. Thanks for the bug-report and ```require.resolve``` tip.
