### ISSUE TITLE
Can't use local plugins

### ISSUE THREAD

**Issue by SamyPesse** [todvora/gitbook-tester#3]
I've tried to use this awesome module to unit tests the new [superscript](https://github.com/GitbookIO/plugin-superscript/blob/master/test/index.js) plugin, but GitBook is not correctly using the plugin:

```
  superscript
creating symlink for plugin gitbook-plugin-superscript to directory /Users/samypesse/Projects/GitBook/plugin-superscript
>  info: 0 plugins to install
>
Done, without error
>  info: loading book configuration....>  OK
>  info: load plugin gitbook-plugin-highlight ....>  OK
>  info: load plugin gitbook-plugin-search ....>  OK
>  info: load plugin gitbook-plugin-sharing ....>  OK
>  info: load plugin gitbook-plugin-fontsettings ....>  OK
>  info: >> 4 plugins loaded
>
>  Template render error: (/var/folders/lq/7nbpx1p13fsdtrpmd0qqpgl00000gn/T/gitbook-tester1151030-4506-sa68dd/README.md) [Line 3, Column 15]
  unknown block tag: sup
    1) should correctly replace by sup html tag

```

The symlink seems to work fine, since it doesn't try to download it from NPM. But then the plugin is not listed during the build.

Is there a way to debug the generated book ?

**Comment by todvora** [comment]
Local plugins has to be removed from book.json before ```gitbook install``` (to prevent npm installation) but attached back after install to be available during ```gitbook build```. It should be fixed in 1.0.2 release. 

Regarding debug - i'll try to add some debug option in following versions of gitbook-tester.

Thanks for bug-report and tips!
