### ISSUE TITLE
Create other file in the book source

### ISSUE THREAD

**Issue by SamyPesse** [todvora/gitbook-tester#5]
It'd be awesome to have a method to write a file in the source directory (string or stream).

**Comment by todvora** [comment]
Thanks for this improvement tip! It is implemented and released as ```1.1.0```. Check the [documentation](https://github.com/todvora/gitbook-tester#withfilepath-content ) and [test usage](https://github.com/todvora/gitbook-tester/blob/master/spec/tester_spec.js#L36). Is it good enough for your needs?

**Comment by todvora** [comment]
One can now attach new files and also read css and js files in the result set. 

Now it seems powerful enough to test the *styles-less* plugin: https://github.com/GitbookIO/plugin-styles-less/pull/2
